# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75b43cfa5683edcc2f81ef5fe3b17640fb5d9d0444f8efb5dd9dfd386fc56cd85a42a0f278286e5b95de840789870025d448598c6b1784d8685563c85b02210c

test:
  secret_key_base: ace453a5de49b0ea96490d9b6bffe46ab4c5e5cab95e48215602cf684510993d4b02a97e67ac035761965fdc0fa8b266be3f121b0623e699b7f134e24ade88b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
